runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip .env, which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:9FzUFcKz/VA+7XJCIy4oBqyUNQe+6lFS1AW9kE3RBuc=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: laravel
  DB_USERNAME: forge
  DB_PASSWORD: BocoSq6xJDQWfayPGajt
  DB_SOCKET: /cloudsql/najaba-201522:europe-west3:najaba
  APP_DEBUG: FALSE

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. project:region:cloudsql-instance
    cloud_sql_instances: najaba-201522:europe-west3:najaba
